apiVersion: v1
data:
  launch.sh: "#!/bin/bash\n\nPASSWORD=$(cat /etc/redis-passwd/passwd)\n\nif [[ \"${HOSTNAME}\"
    == \"redis-0\" ]]; then\n\tredis-server --requirepass ${PASSWORD}\nelse\n\tredis-server
    --slaveof redis-0.redis 6379 --masterauth ${PASSWORD} --requirepass ${PASSWORD}\nfi\n\n"
kind: ConfigMap
metadata:
  creationTimestamp: "2021-03-08T07:50:47Z"
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:launch.sh: {}
    manager: kubectl-create
    operation: Update
    time: "2021-03-08T07:50:47Z"
  name: redis-config
  resourceVersion: "3284608"
  uid: 26b4511d-c86c-46a2-8433-3642a9c43105
